-- migrate:up
ALTER TABLE albums 
ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE songs 
ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
-- migrate:down
ALTER TABLE albums
DROP COLUMN created_at,
DROP COLUMN updated_at;

ALTER TABLE songs
DROP COLUMN created_at,
DROP COLUMN updated_at;
