-- migrate:up
CREATE TABLE artists(
  id SERIAL PRIMARY KEY,
  nickname VARCHAR(200) UNIQUE NOT NULL,
  about TEXT,
  career_start TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- migrate:down
DROP TABLE artists;
